version: "3"
services:
  api:
    tty: true
    stdin_open: true
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8005:8005'
    image: auth-server-fastapi:v1.0
    container_name: fastapi
    volumes:
      - ./api/src:/app
    env_file:
      - ./api/dev.env


